apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-api
  template:
    metadata:
      labels:
        app: ticketing-api
    spec:
      containers:
      - name: ticketing-api
        image: nerochun/ticketing-api:latest
        resources:
          requests:
            # Reserve 200 milli cores for this pod
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-api-service
spec:
  selector:
    app: ticketing-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
